dna_1 = 'ATGTACTATTTAAAAAACACAAACTTTTGGATGTTCGGTTTATTCTTTTTCTTTTACTTTTTTATCATGGGAGCCTACTTCCCGTTTTTCCCGATTTGGCTACATGACATCAACCATATCAGCAAAAGTGATACGGGTATTATTTTTGCCGCTATTTCTCTGTTCTCGCTATTATTCCAACCGCTGTTTGGTCTGCTTTCTGACAAACTCGGGCTGCGCAAATACCTGTGTGATTATTACCGGCATGTTAGTGATGTTTGCGCCGTTCTTTATTTTTATCTTCGGGCCACTGTTACAATACAACATTTTAGTAGGATCGATTGTTGGTGGTATTTATCTAGGCTTTTGTTTTAACGCCGGTGCGCCAGCAGTAGAGGCATTTATTGAGAAAGTCAGCCGTCGCAGTAATTTCGAATTTGGTCGCGCGCGGATGTTTGGCTGTGTTGGCTGGGCGCTGTGTGCCTCGATTGTCGGCATCATGTTCACCATCAATAATCAGTTTGTTTTCTGGCTGGGCTCTGGCTGTGCACTCATCCTCGCCGTTTTACTCTTTTTCGCCAAAACGGATGCGCCCTCTTCTGCCACGGTTGCCAATGCGGTAGGTGCCAACCATTCGGCATTTAGCCTT'
dna_2 = 'CAAAAAGAGAAACTGTTGGGAGAGGAATCGTATCTCCATATTTCTTCTTTCAGCCCCAATCCAAGGGTTGTAGCTGGAACTTTCCATCAGTTCTTCCTTTCTTTTTCCTCTCTAAGCCTTTGCCTTGCTCTGTCACAGTGAAGTCAGCCAGAGCAGGGCTGTTAAACTCTGTGAAATTTGTCATAAGGGTGTCAGGTATTTCTTACTGGCTTCCAAAGAAACATAGATAAAGAAATCTTTCCTGTGGCTTCCCTTGGCAGGCTGCATTCAGAAGGTCTCTCAGTTGAAGAAAGAGCTTGGAGGACAACAGCACAACAGGAGAGTAAAAGATGCCCCAGGGCTGAGGCCTCCGCTCAGGCAGCCGCATCTGGGGTCAATCATACTCACCTTGCCCGGGCCATGCTCCAGCAAAATCAAGCTGTTTTCTTTTGAAAGTTCAAACTCATCAAGATTATGCTGCTCACTCTTATCATTCTGTTGCCAGTAGTTTCAAAATTTAGTTTTGTTAGTCTCTCAGCACCGCAGCACTGGAGCTGTCCTGAAGGTACTCTCGCAGGAAATGGGAATTCTACTTGTGTGGGTAAGTACTCCAATGAAAAGGTGCTCCAGGTCTCCGGGAAACTGCCCC'
dna_3 = 'ATGATTTTGAAATCTTTTCTACTAGGTAATCTAGTATCCTTATGCATGAAGATAATCAATTCGGTCGTTGTGGTCGGACTCTATTATGGATTTCTGACCACATTCTCCATAGGGCCCTCCTATCTCTTCCTTCTCCGAGCTCACGTTATGGAAGAAGGAACCGAGAAGAAGGTATCAGCAACAACTGGTTTTATTACGGGACAGCTCATAATGTTCATATCGATCTATTATGCGCCTCTGCATCTAGCACTGGGTAGACCTCATACAATAACTGTCCTAGCTCTACCGTATCTTTTGTTTCATTTCTTCTGCAATACTCACAAACACTTCTTTGATTATGGATCTACTAACAGAAATTCAATGCGTAATCTCAGCATTCAATGTGTATTCCTGAATAATCTCATTTTTCAATTATTCAATTATTTCATTTATCCAAGTTCAATGTTAGCGAGATTAGTAAATATTTTTATGTTTGGATGCAATAACAAGATTTTATTTGTAACCAGTAGTTTTCTTGGTTGGATAATGGGTCACATTCTATTGATGAAATGGATTGGATTGTTAGTAGTTTGGATACGCAAAAATAGATCTATTCGTAAGTACATTGGATCTAATAAGTCCCTTGTGT'

sum1 = (dna_1.count("TT")*0.02 + (dna_1.count("TC") + dna_1.count("CT"))*0.01 + dna_1.count("CC")*0.01)
print('Повреждённых пар в 1-й последовательности: ', sum1)
sum2 = (dna_2.count("TT")*0.02 + (dna_2.count("TC") + dna_2.count("CT"))*0.01 + dna_2.count("CC")*0.01)
print('Повреждённых пар в 2-й последовательности: ', sum2)
sum3 = (dna_3.count("TT")*0.02 + (dna_3.count("TC") + dna_3.count("CT"))*0.01 + dna_3.count("CC")*0.01)
print('Повреждённых пар в 3-й последовательности: ', sum3)
max = sum1
max_dna = 1
bug_rate1 = sum1 / len(dna_1)
print('Частота встречаемости повреждений в 1-й последовательности равна ', bug_rate1) 
bug_rate2 = sum2 / len(dna_2)
print('Частота встречаемости повреждений во 2-й последовательности равна ', bug_rate2) 
bug_rate3 = sum3 / len(dna_3)
print('Частота встречаемости повреждений в 3-й последовательности равна ', bug_rate3) 
if sum2 > max:
    max = sum2
    max_dna = 2
elif sum3 > max:
    max = sum3
    max_dna = 3

print('Больше всего пострадает последовательность номер ', max_dna)