dna_1 = 'ATGTACTATTTAAAAAACACAAACTTTTGGATGTTCGGTTTATTCTTTTTCTTTTACTTTTTTATCATGGGAGCCTACTTCCCGTTTTTCCCGATTTGGCTACATGACATCAACCATATCAGCAAAAGTGATACGGGTATTATTTTTGCCGCTATTTCTCTGTTCTCGCTATTATTCCAACCGCTGTTTGGTCTGCTTTCTGACAAACTCGGGCTGCGCAAATACCTGTGTGATTATTACCGGCATGTTAGTGATGTTTGCGCCGTTCTTTATTTTTATCTTCGGGCCACTGTTACAATACAACATTTTAGTAGGATCGATTGTTGGTGGTATTTATCTAGGCTTTTGTTTTAACGCCGGTGCGCCAGCAGTAGAGGCATTTATTGAGAAAGTCAGCCGTCGCAGTAATTTCGAATTTGGTCGCGCGCGGATGTTTGGCTGTGTTGGCTGGGCGCTGTGTGCCTCGATTGTCGGCATCATGTTCACCATCAATAATCAGTTTGTTTTCTGGCTGGGCTCTGGCTGTGCACTCATCCTCGCCGTTTTACTCTTTTTCGCCAAAACGGATGCGCCCTCTTCTGCCACGGTTGCCAATGCGGTAGGTGCCAACCATTCGGCATTTAGCCTT'
dna_2 = 'CAAAAAGAGAAACTGTTGGGAGAGGAATCGTATCTCCATATTTCTTCTTTCAGCCCCAATCCAAGGGTTGTAGCTGGAACTTTCCATCAGTTCTTCCTTTCTTTTTCCTCTCTAAGCCTTTGCCTTGCTCTGTCACAGTGAAGTCAGCCAGAGCAGGGCTGTTAAACTCTGTGAAATTTGTCATAAGGGTGTCAGGTATTTCTTACTGGCTTCCAAAGAAACATAGATAAAGAAATCTTTCCTGTGGCTTCCCTTGGCAGGCTGCATTCAGAAGGTCTCTCAGTTGAAGAAAGAGCTTGGAGGACAACAGCACAACAGGAGAGTAAAAGATGCCCCAGGGCTGAGGCCTCCGCTCAGGCAGCCGCATCTGGGGTCAATCATACTCACCTTGCCCGGGCCATGCTCCAGCAAAATCAAGCTGTTTTCTTTTGAAAGTTCAAACTCATCAAGATTATGCTGCTCACTCTTATCATTCTGTTGCCAGTAGTTTCAAAATTTAGTTTTGTTAGTCTCTCAGCACCGCAGCACTGGAGCTGTCCTGAAGGTACTCTCGCAGGAAATGGGAATTCTACTTGTGTGGGTAAGTACTCCAATGAAAAGGTGCTCCAGGTCTCCGGGAAACTGCCCC'
dna_3 = 'ATGATTTTGAAATCTTTTCTACTAGGTAATCTAGTATCCTTATGCATGAAGATAATCAATTCGGTCGTTGTGGTCGGACTCTATTATGGATTTCTGACCACATTCTCCATAGGGCCCTCCTATCTCTTCCTTCTCCGAGCTCACGTTATGGAAGAAGGAACCGAGAAGAAGGTATCAGCAACAACTGGTTTTATTACGGGACAGCTCATAATGTTCATATCGATCTATTATGCGCCTCTGCATCTAGCACTGGGTAGACCTCATACAATAACTGTCCTAGCTCTACCGTATCTTTTGTTTCATTTCTTCTGCAATACTCACAAACACTTCTTTGATTATGGATCTACTAACAGAAATTCAATGCGTAATCTCAGCATTCAATGTGTATTCCTGAATAATCTCATTTTTCAATTATTCAATTATTTCATTTATCCAAGTTCAATGTTAGCGAGATTAGTAAATATTTTTATGTTTGGATGCAATAACAAGATTTTATTTGTAACCAGTAGTTTTCTTGGTTGGATAATGGGTCACATTCTATTGATGAAATGGATTGGATTGTTAGTAGTTTGGATACGCAAAAATAGATCTATTCGTAAGTACATTGGATCTAATAAGTCCCTTGTGT'

p_tt = 0.02
p_cc = 0.01
p_ct = 0.01

sumtt = 0
sumcc= 0
sumct= 0

for i in range(len(dna_1) - 1):
    pair = dna_1[i:i+2]

    if pair == "TT":
        sumtt += 1
    elif pair == "CC":
        sumcc += 1
    elif pair == "CT" or pair == "TC":
        sumct += 1

dna_sum1 = sumtt*0.02 + sumcc*0.01 + sumct*0.01
freq1 = dna_sum1 / len(dna_1)

print('Повреждённых пар в 1-й последовательности: ', dna_sum1)
print('Частота встречаемости повреждений в 1-й последовательности равна ', freq1) 
sumtt = 0
sumcc = 0
sumct = 0

for i in range(len(dna_2) - 1):
    pair = dna_2[i:i+2]

    if pair == "TT":
        sumtt += 1
    elif pair == "CC":
        sumcc += 1
    elif pair == "CT" or pair == "TC":
        sumct += 1

sum_dna2 = sumtt*0.02 + sumcc*0.01 + sumct*0.01
freq2 = sum_dna2 / len(dna_2)

print('Повреждённых пар в 2-й последовательности: ', sum_dna2)
print('Частота встречаемости повреждений во 2-й последовательности равна ', freq2) 


sumtt = 0
sumcc = 0
sumct = 0

for i in range(len(dna_3) - 1):
    pair = dna_3[i:i+2]

    if pair == "TT":
        sumtt += 1
    elif pair == "CC":
        sumcc += 1
    elif pair == "CT" or pair == "TC":
        sumct += 1

sum_dna3 = sumtt*0.02 + sumcc*0.01 + sumct*0.01
freq3 = sum_dna3 / len(dna_3)

print('Повреждённых пар в 3-й последовательности: ', sum_dna3)
print('Частота встречаемости повреждений в 3-й последовательности равна ', freq3) 

if dna_sum1 > sum_dna2 and dna_sum1 > sum_dna3:
    print('Больше всего пострадает последовательность номер 1')
elif sum_dna2 > sum_dna3:
    print('Больше всего пострадает последовательность номер 2')
else:
    print('Больше всего пострадает последовательность номер 3')
